#!/bin/bash
set -ueo pipefail

MNT=/mnt/diod
REMOTE=localhost
#REMOTE=archie

srv() {
    sudo diod -f -d 1 -n -e /proc
}

mnt() {
    sudo mkdir -p $MNT
    sudo umount $MNT || true
    sudo diodmount -n $REMOTE:/proc $MNT
    ls -F $MNT
}

run() {
    LD_PRELOAD=$(pwd)/liboverrides.so \
    REMOTE_PROC_MNT=$MNT \
    "$@"
}

cd "$(dirname $0)"
[[ -e liboverrides.so && liboverrides.so -nt overrides.c ]] || {
    echo compiling
    gcc -fPIC -c overrides.c
    gcc -shared -fPIC -Wl,-soname -Wl,liboverrides.so -o liboverrides.so overrides.o
}
"$@"
